#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : munkres
Version  : 1.1.2
Release  : 3
URL      : https://files.pythonhosted.org/packages/b1/af/366c2b607b6994aa542a9eefd7d4dc1b0abadba396ed84bbbbc17d8d257e/munkres-1.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/b1/af/366c2b607b6994aa542a9eefd7d4dc1b0abadba396ed84bbbbc17d8d257e/munkres-1.1.2.tar.gz
Summary  : Munkres (Hungarian) algorithm for the Assignment Problem
Group    : Development/Tools
License  : Apache-2.0
Requires: munkres-python = %{version}-%{release}
Requires: munkres-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Munkres implementation for Python
---------------------------------
<a href="https://pypi.python.org/pypi/munkres" target="_blank">
<img src="https://img.shields.io/pypi/v/munkres.png">
</a>
<a href="https://travis-ci.org/bmc/munkres">
<img src="https://travis-ci.org/bmc/munkres.svg?branch=master"/>
</a>

%package python
Summary: python components for the munkres package.
Group: Default
Requires: munkres-python3 = %{version}-%{release}

%description python
python components for the munkres package.


%package python3
Summary: python3 components for the munkres package.
Group: Default
Requires: python3-core

%description python3
python3 components for the munkres package.


%prep
%setup -q -n munkres-1.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550500711
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
