#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : munkres
Version  : 1.1.4
Release  : 10
URL      : https://files.pythonhosted.org/packages/fd/41/6a3d0ef908f47d07c31e5d1c2504388c27c39b10b8cf610175b5a789a5c1/munkres-1.1.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/fd/41/6a3d0ef908f47d07c31e5d1c2504388c27c39b10b8cf610175b5a789a5c1/munkres-1.1.4.tar.gz
Summary  : Munkres (Hungarian) algorithm for the Assignment Problem
Group    : Development/Tools
License  : Apache-2.0
Requires: munkres-python = %{version}-%{release}
Requires: munkres-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Introduction
        ============
        
        The Munkres module provides an implementation of the Munkres algorithm
        (also called the Hungarian algorithm or the Kuhn-Munkres algorithm),
        useful for solving the Assignment Problem.

%package python
Summary: python components for the munkres package.
Group: Default
Requires: munkres-python3 = %{version}-%{release}

%description python
python components for the munkres package.


%package python3
Summary: python3 components for the munkres package.
Group: Default
Requires: python3-core
Provides: pypi(munkres)

%description python3
python3 components for the munkres package.


%prep
%setup -q -n munkres-1.1.4
cd %{_builddir}/munkres-1.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600192561
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
